[build]
command = "npm install && npm run build"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NODE_VERSION = "20"

[[redirects]]
from = "/"
to = "/53917586-97ad-49b6-9bd6-51c441316425"
status = 302
